builds:
  - binary: filequeue
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/sugy/filequeue/cmd.version={{.Version}}
      - -X github.com/sugy/filequeue/cmd.commit={{.ShortCommit}}
      - -X github.com/sugy/filequeue/cmd.date={{.Date}}
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: sugy
    name: filequeue
